### PR TITLE
⭐️ Min of 1 star rating 

### PR DESCRIPTION
**Pull request by sassansh**
- Checking on frontend and backend with nice error messages.

### CODE REVIEW

**Review by johnnybcs — COMMENTED** [review]
Screen Shot 2021-08-10 at 11 50 41 AM
what is this?

**Review by laurarodgers — COMMENTED** [review]
Can we make a change directly to the AddReview page so that:

a) if a rate is set to less than 1 star, it is automatically changed onchange to 1 star
b) the option in the Ant Rate component that clears the Rate when clicking it twice is disabled

**Comment by sassansh** [comment]
> Screen Shot 2021-08-10 at 11 50 41 AM
> 
> what is this?

That shouldnt happen easily unless you click submit over and over again. What are the steps to reproduce that issue?

**Comment by johnnybcs** [comment]
I clicked the submit button over and over like a maniac!

**Comment by sassansh** [comment]
> I clicked the submit button over and over like a maniac!

Is that really a use case we need to worry about though?

**Review by johnnybcs — APPROVED** [review]
👍

**Comment by laurarodgers** [comment]
> Can we make a change directly to the AddReview page so that:
> 
> a) if a rate is set to less than 1 star, it is automatically changed onchange to 1 star
> b) the option in the Ant Rate component that clears the Rate when clicking it twice is disabled

**Review by laurarodgers — CHANGES_REQUESTED** [review]
Can we make a change directly to the AddReview page so that:

a) if a rate is set to less than 1 star, it is automatically changed onchange to 1 star
b) the option in the Ant Rate component that clears the Rate when clicking it twice is disabled

**Comment by sassansh** [comment]
> Can we make a change directly to the AddReview page so that:
> 
> a) if a rate is set to less than 1 star, it is automatically changed onchange to 1 star
> b) the option in the Ant Rate component that clears the Rate when clicking it twice is disabled

regarding a, do you mean the default value should be 1? Or that when they submit with a rating 0 zero they change to 1 and submit?

**Comment by laurarodgers** [comment]
> > Can we make a change directly to the AddReview page so that:
> > a) if a rate is set to less than 1 star, it is automatically changed onchange to 1 star
> > b) the option in the Ant Rate component that clears the Rate when clicking it twice is disabled
> 
> regarding a, do you mean the default value should be 1? Or that when they submit with a rating 0 zero they change to 1 and submit

I tried this out in staging and I realize that we're currently using 0 for a "blank/not yet rated" state, and the issue is it is was also being accepted as a genuine rating value.

I think we should keep using 0 as a "blank/not yet rated" state and have the error message say "please enter a rating"? or "please enter a rating for all criteria"??? 

so you've convinced me we shouldn't do the onchange to 1 star or default to 1 star

but we should disable the Ant thing that changes the rating value to 0 if you click the component twice

[Ant example CodePen on the AllowClear attribute ](https://codepen.io/pen/?&editors=001)

**Comment by sassansh** [comment]
Alright changes made:
- The ratings start at 0. But the submit button is disabled until you select a rating above 0 for all of the criterion.
- Clicking the same rating no longer clears it.

chrome-capture

**Comment by sassansh** [comment]
Im not sure why the checks arent running, maybe because @laurarodgers you requested changes?

**Comment by laurarodgers** [comment]
> Im not sure why the checks arent running, maybe because @laurarodgers you requested changes?

Yeah that's what I suspect, which is weird, I wanted to look at it on staging before accepting but I can't because I haven't accepted? Chicken and egg problem lol

**Review by laurarodgers — APPROVED** [review]

**Comment by sassansh** [comment]
Github Actions are down 😂  https://www.githubstatus.com/

image

**Comment by laurarodgers** [comment]
> Github Actions are down 😂 https://www.githubstatus.com/
> 
> image

Well at least it isn't just us 😂

**Comment by sassansh** [comment]
Lol worse status now: 
image

**Comment by sassansh** [comment]
kk, leave this PR until the checks run :)

**Comment by sassansh** [comment]
image
Lets try this again!

**Comment by sassansh** [comment]
image
Running!

**Pull request merged**
