### PR TITLE
backend for Reviews

### PR DESCRIPTION
**Pull request by johnnybcs**
Get, Add, and Edit Review are accessing or changing the DB as expected when I use postman.

### CODE REVIEW

**Review by amirjfr — CHANGES_REQUESTED** [review]
you should remove unnecessary console.logs

**Review by laurarodgers — COMMENTED** [review]
Nevermind, ignore my previous comment - your code is just backend

**Comment by johnnybcs** [comment]
I removed console log. Front end is not ready yet. Even if you don't merge this code you will get the same error above.

**Review by amirjfr — APPROVED** [review]

**Comment by laurarodgers** [comment]
> I removed console log. Front end is not ready yet. Even if you don't merge this code you will get the same error above.

Yyep, I'll learn to read one of these days.

**Pull request merged**
