### PR TITLE
Changes to AddReview code

### PR DESCRIPTION
**Pull request by laurarodgers**
Changes to AddReview to remove duplicate code. Should not affect functionality.

### CODE REVIEW

**Review by sassansh — APPROVED** [review]
Flawless! Tested! So much cleaner ✨

**Comment by sassansh** [comment]
Some responsiveness issues (unnecessary warping, theres plenty space)on the place's name on my screen though: 
image
@johnnybcs

**Comment by laurarodgers** [comment]
> Some responsiveness issues (unnecessary warping, theres plenty space)on the place's name on my screen though:
> image
> @johnnybcs

Looks like this is also the case on main (not related to these particular code changes)
and my hunch is it has to do with column widths not being set for XXL screen

**Comment by sassansh** [comment]
> > Some responsiveness issues (unnecessary warping, theres plenty space)on the place's name on my screen though:
> > @johnnybcs
> 
> Looks like this is also the case on main (not related to these particular code changes)
> and my hunch is it has to do with column widths not being set for XXL screen

True, that issue is not relevant to this pull request. Go ahead and merge, we'll deal with that separately.

**Pull request merged**
