### PR TITLE
🧼 JavaScript Standard Style Fix & Super-linter Action

### PR DESCRIPTION
**Pull request by sassansh**
- 🎨 Cleaned up a lot of css code style issues
- 🤖 Used `npx semistandard --fix` to fix a lot of javascript code style issues (https://github.com/standard/semistandard)
- 🚔 Setup an auto lint action to show us style issues on changed files when pull request on main happens.
  - [Super-linter](https://github.com/marketplace/actions/super-linter) action

### CODE REVIEW

**Review by johnnybcs — COMMENTED** [review]
Isn't it good coding practice to have a semi colon at the end of a line? 

All the semi colons are being deleted.

**Comment by sassansh** [comment]
> Isn't it good coding practice to have a semi colon at the end of a line?
> 
> All the semi colons are being deleted.

I found that weird as well. I thought they were required. Turns out they are optional and code looks a lot cleaner without them.
https://flaviocopes.com/javascript-automatic-semicolon-insertion/

Let me know your thoughts.

**Comment by sassansh** [comment]
Check out this section on their own website:

> I disagree with rule X, can you change it?
No. The whole point of standard is to save you time by avoiding bikeshedding about code style. There are lots of debates online about tabs vs. spaces, etc. that will never be resolved. These debates just distract from getting stuff done. At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions. Hopefully, users see the value in that over defending their own opinions.

https://standardjs.com/#i-disagree-with-rule-x-can-you-change-it

**Comment by sassansh** [comment]
You win @johnnybcs! semicolons are back! Our lint actions wont complain anymore. All checks passing.

**Review by amirjfr — APPROVED** [review]

**Comment by sassansh** [comment]
Lint Code Base
Test Frontend Build

**Comment by sassansh** [comment]
Awesome! Going forward all of our code is linted for any obvious issues, I have fixed all existing issues. 

🆕 ⚠️  **Required:** These 2 checks must pass to be able to merge going forward:
- Lint Code Base
- Test Frontend Build
@amirjfr @johnnybcs @laurarodgers

**Review by johnnybcs — APPROVED** [review]
:)

**Pull request merged**
