### PR TITLE
User Profile

### PR DESCRIPTION
**Pull request by johnnybcs**
User profile shows avatar, name, groups joined, and reviews.

Amir's user doesn't work because his user contains group_ids that don't exist in groups.

### CODE REVIEW

**Comment by sassansh** [comment]
Not the best use of space: 
image
For groups and places maybe try reusing the components we already have for groups, grouplist, places, place list. Or make something similar. Groups would look much better with their logos. Cant tell which group the places belong to either. Let me see if i can sketch something up. This looks a little raw.

**Comment by sassansh** [comment]
Desktop:

image

**Comment by sassansh** [comment]
Mobile: 

image

**Comment by johnnybcs** [comment]
@sassansh  Did you already make the code changes to fix it, or is that just like a picture of what you want me to make it look like?

**Comment by sassansh** [comment]
> @sassansh Did you already make the code changes to fix it, or is that just like a picture of what you want me to make it look like?

Just sketches on how it could be improved. I haven't implemented any of it. Hoping you can take parts of it and include it in your implementation.

**Comment by johnnybcs** [comment]
Looks nice.

**Comment by amirjfr** [comment]
> User profile shows avatar, name, groups joined, and reviews.
> 
> Amir's user doesn't work because his user contains group_ids that don't exist in groups.

I deleted the extra groups. Sorry I was testing something.

**Comment by sassansh** [comment]
5CB29E3F-300E-42FC-B4F8-D5948A30FFC1
Looking better already 😍

**Comment by sassansh** [comment]
E53CE0E5-F29B-4B28-BA37-49D66D021D2F
Group photos 🤩🤩

**Review by sassansh — APPROVED** [review]
✅ I think this is quality enough to be merged. But it definitely still needs:
- 📱 mobile view optimizations (sketched)
- 📄 And it be really useful to show the category and group for each review. (Sketched)

⚠️ So continue working on it and merge when you’re ready or create a separate pull request later for those improvements. 

AMAZING JOB 👏🏻 thanks for taking my designs into account 🥰

**Pull request merged**
